// Generated by CoffeeScript 1.7.1
var fs, http, io, page, path, server, sio, url;

http = require('http');

url = require('url');

io = require('socket.io');

fs = require('fs');

path = require('path');

page = path.resolve('page.html');

sio = path.resolve('js/socket.io.js');

server = http.createServer(function(req, res) {
  var html, js, pathname;
  pathname = url.parse(req.url).pathname;
  console.log(pathname);
  switch (pathname) {
    case '/socket.io.js':
      js = fs.readFileSync(sio);
      res.writeHead(200, {
        'Content-Type': 'text/javascript'
      });
      return res.end(js);
    default:
      html = fs.readFileSync(page);
      res.writeHead(200, {
        'Content-Type': 'text/html'
      });
      return res.end(html);
  }
});

server.listen(8888);

io = io(server);

io.on('connection', function(socket) {
  return socket.emit('message', {
    message: 'hello world'
  });
});
